language: cpp
compiler:
  - clang
  - gcc
before_script:
  - cmake -D CMAKE_BUILD_TYPE=Debug .
script: make
after_script:
  - make test
  - make install
notifications:
  email:
    on_success: always
    on_failure: always
